# Generated by Django 5.2.11 on 2026-02-12 23:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GlobalSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_language",
                    models.CharField(
                        choices=[("fa", "Persian"), ("en", "English")],
                        default="fa",
                        max_length=8,
                    ),
                ),
                (
                    "slug_max_length",
                    models.PositiveSmallIntegerField(
                        default=70,
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(200),
                        ],
                    ),
                ),
                (
                    "language_calendar_mapping",
                    models.JSONField(
                        default=dict,
                        help_text="نگاشت زبان به تقویم. مثال: {'fa': 'jalali', 'en': 'gregorian', 'ar': 'hijri'}",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات سراسری",
                "verbose_name_plural": "تنظیمات سراسری",
            },
        ),
    ]
