# Generated by Django 5.2.11 on 2026-02-12 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GlobalSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("default_language", models.CharField(default="fa", max_length=10)),
                ("slug_max_length", models.PositiveIntegerField(default=70)),
                (
                    "language_calendar_mapping",
                    models.JSONField(
                        default=dict,
                        help_text="Mapping زبان به تقویم. مثال: {'fa': 'jalali', 'en': 'gregorian'}",
                    ),
                ),
            ],
            options={
                "verbose_name": "Global Settings",
                "verbose_name_plural": "Global Settings",
            },
        ),
    ]
