# Generated by Django 5.2.11 on 2026-02-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlugContractSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=70)),
                ("language", models.CharField(default="fa", max_length=8)),
            ],
            options={
                "verbose_name": "نمونه قرارداد اسلاگ",
                "verbose_name_plural": "نمونه\u200cهای قرارداد اسلاگ",
            },
        ),
    ]
